<?xml version = "1.0" ?>
<?xml-stylesheet type="text/xsl" href="SystemBOM.xsl"?>
<!DOCTYPE GRID [
  <!ELEMENT GRID (BANDS, COLUMNS, ROWS*)>
  <!ATTLIST GRID ExportVersion CDATA #REQUIRED>
  <!ELEMENT BANDS (BAND*)>
  <!ELEMENT BAND EMPTY>
  <!ATTLIST BAND Index CDATA #REQUIRED>
  <!ATTLIST BAND Caption CDATA #IMPLIED>
  <!ELEMENT COLUMNS (COLUMN*)>
  <!ELEMENT COLUMN EMPTY>
  <!ATTLIST COLUMN Name CDATA #REQUIRED>
  <!ATTLIST COLUMN Caption CDATA #IMPLIED>
  <!ATTLIST COLUMN Index CDATA #REQUIRED>
  <!ATTLIST COLUMN BandIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN RowIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN ColIndex CDATA #REQUIRED>
  <!ATTLIST COLUMN Width CDATA #IMPLIED>
  <!ELEMENT GROUP (GROUP*, ROW*)>
  <!ATTLIST GROUP GroupText CDATA #IMPLIED>
  <!ELEMENT ROWS (ROW*)>
  <!ELEMENT ROW EMPTY>
  <!ATTLIST ROW Address1 CDATA #IMPLIED>
  <!ATTLIST ROW Address2 CDATA #IMPLIED>
  <!ATTLIST ROW Address3 CDATA #IMPLIED>
  <!ATTLIST ROW Address4 CDATA #IMPLIED>
  <!ATTLIST ROW Angle_de_diffusion CDATA #IMPLIED>
  <!ATTLIST ROW Application_BuildNumber CDATA #IMPLIED>
  <!ATTLIST ROW ApprovedBy CDATA #IMPLIED>
  <!ATTLIST ROW Author CDATA #IMPLIED>
  <!ATTLIST ROW CheckedBy CDATA #IMPLIED>
  <!ATTLIST ROW Code_IPC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEDEC CDATA #IMPLIED>
  <!ATTLIST ROW Code_JEITA CDATA #IMPLIED>
  <!ATTLIST ROW Comment CDATA #IMPLIED>
  <!ATTLIST ROW CompanyName CDATA #IMPLIED>
  <!ATTLIST ROW Component_Kind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentKind CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink1URL CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2Description CDATA #IMPLIED>
  <!ATTLIST ROW ComponentLink2URL CDATA #IMPLIED>
  <!ATTLIST ROW Configuration_des_contacts CDATA #IMPLIED>
  <!ATTLIST ROW Courant CDATA #IMPLIED>
  <!ATTLIST ROW Courant_de_contact_max_ CDATA #IMPLIED>
  <!ATTLIST ROW CurrentDate CDATA #IMPLIED>
  <!ATTLIST ROW CurrentTime CDATA #IMPLIED>
  <!ATTLIST ROW Date CDATA #IMPLIED>
  <!ATTLIST ROW Date_de_cr_ation CDATA #IMPLIED>
  <!ATTLIST ROW Derni_re_r_vision CDATA #IMPLIED>
  <!ATTLIST ROW Description CDATA #IMPLIED>
  <!ATTLIST ROW Designator CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_X_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Designator_Y_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW DesignItemId CDATA #IMPLIED>
  <!ATTLIST ROW Document CDATA #IMPLIED>
  <!ATTLIST ROW DocumentFullPathAndName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentName CDATA #IMPLIED>
  <!ATTLIST ROW DocumentNumber CDATA #IMPLIED>
  <!ATTLIST ROW DrawnBy CDATA #IMPLIED>
  <!ATTLIST ROW Edition CDATA #IMPLIED>
  <!ATTLIST ROW Engineer CDATA #IMPLIED>
  <!ATTLIST ROW Fabriquant CDATA #IMPLIED>
  <!ATTLIST ROW Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Force__fonctionnement CDATA #IMPLIED>
  <!ATTLIST ROW Hauteur CDATA #IMPLIED>
  <!ATTLIST ROW Height_Mil_ CDATA #IMPLIED>
  <!ATTLIST ROW Height_mm_ CDATA #IMPLIED>
  <!ATTLIST ROW Ibis_Model CDATA #IMPLIED>
  <!ATTLIST ROW ImagePath CDATA #IMPLIED>
  <!ATTLIST ROW Index CDATA #IMPLIED>
  <!ATTLIST ROW ItemGUID CDATA #IMPLIED>
  <!ATTLIST ROW Library_Name CDATA #IMPLIED>
  <!ATTLIST ROW Library_Reference CDATA #IMPLIED>
  <!ATTLIST ROW LibRef CDATA #IMPLIED>
  <!ATTLIST ROW Lien_GCC CDATA #IMPLIED>
  <!ATTLIST ROW LogicalDesignator CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_1 CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number CDATA #IMPLIED>
  <!ATTLIST ROW Manufacturer_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Model_Footprint CDATA #IMPLIED>
  <!ATTLIST ROW Models CDATA #IMPLIED>
  <!ATTLIST ROW ModifiedDate CDATA #IMPLIED>
  <!ATTLIST ROW MSL CDATA #IMPLIED>
  <!ATTLIST ROW Organization CDATA #IMPLIED>
  <!ATTLIST ROW PartType CDATA #IMPLIED>
  <!ATTLIST ROW PCB3D CDATA #IMPLIED>
  <!ATTLIST ROW PhysicalPath CDATA #IMPLIED>
  <!ATTLIST ROW Pic_de_longueur_d_onde CDATA #IMPLIED>
  <!ATTLIST ROW Pins CDATA #IMPLIED>
  <!ATTLIST ROW Poid CDATA #IMPLIED>
  <!ATTLIST ROW Pricing CDATA #IMPLIED>
  <!ATTLIST ROW Prix CDATA #IMPLIED>
  <!ATTLIST ROW Project CDATA #IMPLIED>
  <!ATTLIST ROW ProjectName CDATA #IMPLIED>
  <!ATTLIST ROW Puissance CDATA #IMPLIED>
  <!ATTLIST ROW Puissance_lumineuse CDATA #IMPLIED>
  <!ATTLIST ROW Quantity CDATA #IMPLIED>
  <!ATTLIST ROW R_f_rence_fabriquant CDATA #IMPLIED>
  <!ATTLIST ROW Revision CDATA #IMPLIED>
  <!ATTLIST ROW RevisionGUID CDATA #IMPLIED>
  <!ATTLIST ROW Rule CDATA #IMPLIED>
  <!ATTLIST ROW Semi_conducteur CDATA #IMPLIED>
  <!ATTLIST ROW SheetNumber CDATA #IMPLIED>
  <!ATTLIST ROW SheetTotal CDATA #IMPLIED>
  <!ATTLIST ROW Signal_Integrity CDATA #IMPLIED>
  <!ATTLIST ROW Simulation CDATA #IMPLIED>
  <!ATTLIST ROW SourceLibraryName CDATA #IMPLIED>
  <!ATTLIST ROW Sub_Parts CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Currency_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Order_Qty_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Part_Number_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Stock_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Subtotal_1 CDATA #IMPLIED>
  <!ATTLIST ROW Supplier_Unit_Price_1 CDATA #IMPLIED>
  <!ATTLIST ROW SVHC CDATA #IMPLIED>
  <!ATTLIST ROW Tension CDATA #IMPLIED>
  <!ATTLIST ROW Tension_DC_nominale_du_contact CDATA #IMPLIED>
  <!ATTLIST ROW Terminaisons_commutateur CDATA #IMPLIED>
  <!ATTLIST ROW Time CDATA #IMPLIED>
  <!ATTLIST ROW Title CDATA #IMPLIED>
  <!ATTLIST ROW Tr CDATA #IMPLIED>
  <!ATTLIST ROW Type CDATA #IMPLIED>
  <!ATTLIST ROW Type_d_actionnement CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdName CDATA #IMPLIED>
  <!ATTLIST ROW UniqueIdPath CDATA #IMPLIED>
  <!ATTLIST ROW Variant CDATA #IMPLIED>
  <!ATTLIST ROW VaultGUID CDATA #IMPLIED>
  <!ATTLIST ROW Vd CDATA #IMPLIED>
  <!ATTLIST ROW _ CDATA #IMPLIED>
  <!ATTLIST ROW _ID_ CDATA #IMPLIED>
  <!ATTLIST ROW _PARENTID_ CDATA #IMPLIED>
]>
<GRID ExportVersion="1.0">
  <BANDS>
    <BAND Index="0" Caption=""></BAND>
  </BANDS>
  <COLUMNS>
    <COLUMN Name="Address1" Caption="Address1" Index="0" BandIndex="0" RowIndex="0" ColIndex="0" Width="100"></COLUMN>
    <COLUMN Name="Address2" Caption="Address2" Index="1" BandIndex="0" RowIndex="0" ColIndex="1" Width="100"></COLUMN>
    <COLUMN Name="Address3" Caption="Address3" Index="2" BandIndex="0" RowIndex="0" ColIndex="2" Width="100"></COLUMN>
    <COLUMN Name="Address4" Caption="Address4" Index="3" BandIndex="0" RowIndex="0" ColIndex="3" Width="100"></COLUMN>
    <COLUMN Name="Angle_de_diffusion" Caption="Angle de diffusion" Index="4" BandIndex="0" RowIndex="0" ColIndex="4" Width="100"></COLUMN>
    <COLUMN Name="Application_BuildNumber" Caption="Application_BuildNumber" Index="5" BandIndex="0" RowIndex="0" ColIndex="5" Width="100"></COLUMN>
    <COLUMN Name="ApprovedBy" Caption="ApprovedBy" Index="6" BandIndex="0" RowIndex="0" ColIndex="6" Width="100"></COLUMN>
    <COLUMN Name="Author" Caption="Author" Index="7" BandIndex="0" RowIndex="0" ColIndex="7" Width="100"></COLUMN>
    <COLUMN Name="CheckedBy" Caption="CheckedBy" Index="8" BandIndex="0" RowIndex="0" ColIndex="8" Width="100"></COLUMN>
    <COLUMN Name="Code_IPC" Caption="Code_IPC" Index="9" BandIndex="0" RowIndex="0" ColIndex="9" Width="100"></COLUMN>
    <COLUMN Name="Code_JEDEC" Caption="Code_JEDEC" Index="10" BandIndex="0" RowIndex="0" ColIndex="10" Width="100"></COLUMN>
    <COLUMN Name="Code_JEITA" Caption="Code_JEITA" Index="11" BandIndex="0" RowIndex="0" ColIndex="11" Width="100"></COLUMN>
    <COLUMN Name="Comment" Caption="Comment" Index="12" BandIndex="0" RowIndex="0" ColIndex="12" Width="100"></COLUMN>
    <COLUMN Name="CompanyName" Caption="CompanyName" Index="13" BandIndex="0" RowIndex="0" ColIndex="13" Width="100"></COLUMN>
    <COLUMN Name="Component_Kind" Caption="Component Kind" Index="14" BandIndex="0" RowIndex="0" ColIndex="14" Width="100"></COLUMN>
    <COLUMN Name="ComponentKind" Caption="ComponentKind" Index="15" BandIndex="0" RowIndex="0" ColIndex="15" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1Description" Caption="ComponentLink1Description" Index="16" BandIndex="0" RowIndex="0" ColIndex="16" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink1URL" Caption="ComponentLink1URL" Index="17" BandIndex="0" RowIndex="0" ColIndex="17" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2Description" Caption="ComponentLink2Description" Index="18" BandIndex="0" RowIndex="0" ColIndex="18" Width="100"></COLUMN>
    <COLUMN Name="ComponentLink2URL" Caption="ComponentLink2URL" Index="19" BandIndex="0" RowIndex="0" ColIndex="19" Width="100"></COLUMN>
    <COLUMN Name="Configuration_des_contacts" Caption="Configuration des contacts" Index="20" BandIndex="0" RowIndex="0" ColIndex="20" Width="100"></COLUMN>
    <COLUMN Name="Courant" Caption="Courant" Index="21" BandIndex="0" RowIndex="0" ColIndex="21" Width="100"></COLUMN>
    <COLUMN Name="Courant_de_contact_max_" Caption="Courant de contact max." Index="22" BandIndex="0" RowIndex="0" ColIndex="22" Width="100"></COLUMN>
    <COLUMN Name="CurrentDate" Caption="CurrentDate" Index="23" BandIndex="0" RowIndex="0" ColIndex="23" Width="100"></COLUMN>
    <COLUMN Name="CurrentTime" Caption="CurrentTime" Index="24" BandIndex="0" RowIndex="0" ColIndex="24" Width="100"></COLUMN>
    <COLUMN Name="Date" Caption="Date" Index="25" BandIndex="0" RowIndex="0" ColIndex="25" Width="100"></COLUMN>
    <COLUMN Name="Date_de_cr_ation" Caption="Date de cr&#233;ation" Index="26" BandIndex="0" RowIndex="0" ColIndex="26" Width="100"></COLUMN>
    <COLUMN Name="Derni_re_r_vision" Caption="Derni&#233;re r&#233;vision" Index="27" BandIndex="0" RowIndex="0" ColIndex="27" Width="100"></COLUMN>
    <COLUMN Name="Description" Caption="Description" Index="28" BandIndex="0" RowIndex="0" ColIndex="28" Width="100"></COLUMN>
    <COLUMN Name="Designator" Caption="Designator" Index="29" BandIndex="0" RowIndex="0" ColIndex="29" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_Mil_" Caption="Designator-X&#40;Mil&#41;" Index="30" BandIndex="0" RowIndex="0" ColIndex="30" Width="100"></COLUMN>
    <COLUMN Name="Designator_X_mm_" Caption="Designator-X&#40;mm&#41;" Index="31" BandIndex="0" RowIndex="0" ColIndex="31" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_Mil_" Caption="Designator-Y&#40;Mil&#41;" Index="32" BandIndex="0" RowIndex="0" ColIndex="32" Width="100"></COLUMN>
    <COLUMN Name="Designator_Y_mm_" Caption="Designator-Y&#40;mm&#41;" Index="33" BandIndex="0" RowIndex="0" ColIndex="33" Width="100"></COLUMN>
    <COLUMN Name="DesignItemId" Caption="DesignItemId" Index="34" BandIndex="0" RowIndex="0" ColIndex="34" Width="100"></COLUMN>
    <COLUMN Name="Document" Caption="Document" Index="35" BandIndex="0" RowIndex="0" ColIndex="35" Width="100"></COLUMN>
    <COLUMN Name="DocumentFullPathAndName" Caption="DocumentFullPathAndName" Index="36" BandIndex="0" RowIndex="0" ColIndex="36" Width="100"></COLUMN>
    <COLUMN Name="DocumentName" Caption="DocumentName" Index="37" BandIndex="0" RowIndex="0" ColIndex="37" Width="100"></COLUMN>
    <COLUMN Name="DocumentNumber" Caption="DocumentNumber" Index="38" BandIndex="0" RowIndex="0" ColIndex="38" Width="100"></COLUMN>
    <COLUMN Name="DrawnBy" Caption="DrawnBy" Index="39" BandIndex="0" RowIndex="0" ColIndex="39" Width="100"></COLUMN>
    <COLUMN Name="Edition" Caption="Edition" Index="40" BandIndex="0" RowIndex="0" ColIndex="40" Width="100"></COLUMN>
    <COLUMN Name="Engineer" Caption="Engineer" Index="41" BandIndex="0" RowIndex="0" ColIndex="41" Width="100"></COLUMN>
    <COLUMN Name="Fabriquant" Caption="Fabriquant" Index="42" BandIndex="0" RowIndex="0" ColIndex="42" Width="100"></COLUMN>
    <COLUMN Name="Footprint" Caption="Footprint" Index="43" BandIndex="0" RowIndex="0" ColIndex="43" Width="100"></COLUMN>
    <COLUMN Name="Force__fonctionnement" Caption="Force, fonctionnement" Index="44" BandIndex="0" RowIndex="0" ColIndex="44" Width="100"></COLUMN>
    <COLUMN Name="Hauteur" Caption="Hauteur" Index="45" BandIndex="0" RowIndex="0" ColIndex="45" Width="100"></COLUMN>
    <COLUMN Name="Height_Mil_" Caption="Height&#40;Mil&#41;" Index="46" BandIndex="0" RowIndex="0" ColIndex="46" Width="100"></COLUMN>
    <COLUMN Name="Height_mm_" Caption="Height&#40;mm&#41;" Index="47" BandIndex="0" RowIndex="0" ColIndex="47" Width="100"></COLUMN>
    <COLUMN Name="Ibis_Model" Caption="Ibis Model" Index="48" BandIndex="0" RowIndex="0" ColIndex="48" Width="100"></COLUMN>
    <COLUMN Name="ImagePath" Caption="ImagePath" Index="49" BandIndex="0" RowIndex="0" ColIndex="49" Width="100"></COLUMN>
    <COLUMN Name="Index" Caption="Index" Index="50" BandIndex="0" RowIndex="0" ColIndex="50" Width="100"></COLUMN>
    <COLUMN Name="ItemGUID" Caption="ItemGUID" Index="51" BandIndex="0" RowIndex="0" ColIndex="51" Width="100"></COLUMN>
    <COLUMN Name="Library_Name" Caption="Library Name" Index="52" BandIndex="0" RowIndex="0" ColIndex="52" Width="100"></COLUMN>
    <COLUMN Name="Library_Reference" Caption="Library Reference" Index="53" BandIndex="0" RowIndex="0" ColIndex="53" Width="100"></COLUMN>
    <COLUMN Name="LibRef" Caption="LibRef" Index="54" BandIndex="0" RowIndex="0" ColIndex="54" Width="100"></COLUMN>
    <COLUMN Name="Lien_GCC" Caption="Lien GCC" Index="55" BandIndex="0" RowIndex="0" ColIndex="55" Width="100"></COLUMN>
    <COLUMN Name="LogicalDesignator" Caption="LogicalDesignator" Index="56" BandIndex="0" RowIndex="0" ColIndex="56" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer" Caption="Manufacturer" Index="57" BandIndex="0" RowIndex="0" ColIndex="57" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_1" Caption="Manufacturer 1" Index="58" BandIndex="0" RowIndex="0" ColIndex="58" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number" Caption="Manufacturer Part Number" Index="59" BandIndex="0" RowIndex="0" ColIndex="59" Width="100"></COLUMN>
    <COLUMN Name="Manufacturer_Part_Number_1" Caption="Manufacturer Part Number 1" Index="60" BandIndex="0" RowIndex="0" ColIndex="60" Width="100"></COLUMN>
    <COLUMN Name="Model_Footprint" Caption="Model:Footprint" Index="61" BandIndex="0" RowIndex="0" ColIndex="61" Width="100"></COLUMN>
    <COLUMN Name="Models" Caption="Models" Index="62" BandIndex="0" RowIndex="0" ColIndex="62" Width="100"></COLUMN>
    <COLUMN Name="ModifiedDate" Caption="ModifiedDate" Index="63" BandIndex="0" RowIndex="0" ColIndex="63" Width="100"></COLUMN>
    <COLUMN Name="MSL" Caption="MSL" Index="64" BandIndex="0" RowIndex="0" ColIndex="64" Width="100"></COLUMN>
    <COLUMN Name="Organization" Caption="Organization" Index="65" BandIndex="0" RowIndex="0" ColIndex="65" Width="100"></COLUMN>
    <COLUMN Name="PartType" Caption="PartType" Index="66" BandIndex="0" RowIndex="0" ColIndex="66" Width="100"></COLUMN>
    <COLUMN Name="PCB3D" Caption="PCB3D" Index="67" BandIndex="0" RowIndex="0" ColIndex="67" Width="100"></COLUMN>
    <COLUMN Name="PhysicalPath" Caption="PhysicalPath" Index="68" BandIndex="0" RowIndex="0" ColIndex="68" Width="100"></COLUMN>
    <COLUMN Name="Pic_de_longueur_d_onde" Caption="Pic de longueur d&#39;onde" Index="69" BandIndex="0" RowIndex="0" ColIndex="69" Width="100"></COLUMN>
    <COLUMN Name="Pins" Caption="Pins" Index="70" BandIndex="0" RowIndex="0" ColIndex="70" Width="100"></COLUMN>
    <COLUMN Name="Poid" Caption="Poid" Index="71" BandIndex="0" RowIndex="0" ColIndex="71" Width="100"></COLUMN>
    <COLUMN Name="Pricing" Caption="Pricing" Index="72" BandIndex="0" RowIndex="0" ColIndex="72" Width="100"></COLUMN>
    <COLUMN Name="Prix" Caption="Prix" Index="73" BandIndex="0" RowIndex="0" ColIndex="73" Width="100"></COLUMN>
    <COLUMN Name="Project" Caption="Project" Index="74" BandIndex="0" RowIndex="0" ColIndex="74" Width="100"></COLUMN>
    <COLUMN Name="ProjectName" Caption="ProjectName" Index="75" BandIndex="0" RowIndex="0" ColIndex="75" Width="100"></COLUMN>
    <COLUMN Name="Puissance" Caption="Puissance" Index="76" BandIndex="0" RowIndex="0" ColIndex="76" Width="100"></COLUMN>
    <COLUMN Name="Puissance_lumineuse" Caption="Puissance lumineuse" Index="77" BandIndex="0" RowIndex="0" ColIndex="77" Width="100"></COLUMN>
    <COLUMN Name="Quantity" Caption="Quantity" Index="78" BandIndex="0" RowIndex="0" ColIndex="78" Width="100"></COLUMN>
    <COLUMN Name="R_f_rence_fabriquant" Caption="R&#233;f&#233;rence fabriquant" Index="79" BandIndex="0" RowIndex="0" ColIndex="79" Width="100"></COLUMN>
    <COLUMN Name="Revision" Caption="Revision" Index="80" BandIndex="0" RowIndex="0" ColIndex="80" Width="100"></COLUMN>
    <COLUMN Name="RevisionGUID" Caption="RevisionGUID" Index="81" BandIndex="0" RowIndex="0" ColIndex="81" Width="100"></COLUMN>
    <COLUMN Name="Rule" Caption="Rule" Index="82" BandIndex="0" RowIndex="0" ColIndex="82" Width="100"></COLUMN>
    <COLUMN Name="Semi_conducteur" Caption="Semi-conducteur" Index="83" BandIndex="0" RowIndex="0" ColIndex="83" Width="100"></COLUMN>
    <COLUMN Name="SheetNumber" Caption="SheetNumber" Index="84" BandIndex="0" RowIndex="0" ColIndex="84" Width="100"></COLUMN>
    <COLUMN Name="SheetTotal" Caption="SheetTotal" Index="85" BandIndex="0" RowIndex="0" ColIndex="85" Width="100"></COLUMN>
    <COLUMN Name="Signal_Integrity" Caption="Signal Integrity" Index="86" BandIndex="0" RowIndex="0" ColIndex="86" Width="100"></COLUMN>
    <COLUMN Name="Simulation" Caption="Simulation" Index="87" BandIndex="0" RowIndex="0" ColIndex="87" Width="100"></COLUMN>
    <COLUMN Name="SourceLibraryName" Caption="SourceLibraryName" Index="88" BandIndex="0" RowIndex="0" ColIndex="88" Width="100"></COLUMN>
    <COLUMN Name="Sub_Parts" Caption="Sub-Parts" Index="89" BandIndex="0" RowIndex="0" ColIndex="89" Width="100"></COLUMN>
    <COLUMN Name="Supplier_1" Caption="Supplier 1" Index="90" BandIndex="0" RowIndex="0" ColIndex="90" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Currency_1" Caption="Supplier Currency 1" Index="91" BandIndex="0" RowIndex="0" ColIndex="91" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Order_Qty_1" Caption="Supplier Order Qty 1" Index="92" BandIndex="0" RowIndex="0" ColIndex="92" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Part_Number_1" Caption="Supplier Part Number 1" Index="93" BandIndex="0" RowIndex="0" ColIndex="93" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Stock_1" Caption="Supplier Stock 1" Index="94" BandIndex="0" RowIndex="0" ColIndex="94" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Subtotal_1" Caption="Supplier Subtotal 1" Index="95" BandIndex="0" RowIndex="0" ColIndex="95" Width="100"></COLUMN>
    <COLUMN Name="Supplier_Unit_Price_1" Caption="Supplier Unit Price 1" Index="96" BandIndex="0" RowIndex="0" ColIndex="96" Width="100"></COLUMN>
    <COLUMN Name="SVHC" Caption="SVHC" Index="97" BandIndex="0" RowIndex="0" ColIndex="97" Width="100"></COLUMN>
    <COLUMN Name="Tension" Caption="Tension" Index="98" BandIndex="0" RowIndex="0" ColIndex="98" Width="100"></COLUMN>
    <COLUMN Name="Tension_DC_nominale_du_contact" Caption="Tension DC nominale du contact" Index="99" BandIndex="0" RowIndex="0" ColIndex="99" Width="100"></COLUMN>
    <COLUMN Name="Terminaisons_commutateur" Caption="Terminaisons commutateur" Index="100" BandIndex="0" RowIndex="0" ColIndex="100" Width="100"></COLUMN>
    <COLUMN Name="Time" Caption="Time" Index="101" BandIndex="0" RowIndex="0" ColIndex="101" Width="100"></COLUMN>
    <COLUMN Name="Title" Caption="Title" Index="102" BandIndex="0" RowIndex="0" ColIndex="102" Width="100"></COLUMN>
    <COLUMN Name="Tr" Caption="Tr" Index="103" BandIndex="0" RowIndex="0" ColIndex="103" Width="100"></COLUMN>
    <COLUMN Name="Type" Caption="Type" Index="104" BandIndex="0" RowIndex="0" ColIndex="104" Width="100"></COLUMN>
    <COLUMN Name="Type_d_actionnement" Caption="Type d&#39;actionnement" Index="105" BandIndex="0" RowIndex="0" ColIndex="105" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdName" Caption="UniqueIdName" Index="106" BandIndex="0" RowIndex="0" ColIndex="106" Width="100"></COLUMN>
    <COLUMN Name="UniqueIdPath" Caption="UniqueIdPath" Index="107" BandIndex="0" RowIndex="0" ColIndex="107" Width="100"></COLUMN>
    <COLUMN Name="Variant" Caption="Variant" Index="108" BandIndex="0" RowIndex="0" ColIndex="108" Width="100"></COLUMN>
    <COLUMN Name="VaultGUID" Caption="VaultGUID" Index="109" BandIndex="0" RowIndex="0" ColIndex="109" Width="100"></COLUMN>
    <COLUMN Name="Vd" Caption="Vd" Index="110" BandIndex="0" RowIndex="0" ColIndex="110" Width="100"></COLUMN>
    <COLUMN Name="_" Caption="&#35;" Index="111" BandIndex="0" RowIndex="0" ColIndex="111" Width="100"></COLUMN>
    <COLUMN Name="_ID_" Caption="&#37;ID&#37;" Index="112" BandIndex="0" RowIndex="0" ColIndex="112" Width="100"></COLUMN>
    <COLUMN Name="_PARENTID_" Caption="&#37;PARENTID&#37;" Index="113" BandIndex="0" RowIndex="0" ColIndex="113" Width="100"></COLUMN>
  </COLUMNS>
  <ROWS>
    <ROW Address1="" Address2="" Address3="" Address4="" Angle_de_diffusion="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Code_JEITA="" Comment="47&#181;F" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink1URL="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink2Description="http://www.farnell.com/cad/1703907.zip" ComponentLink2URL="http://www.farnell.com/cad/1703907.zip" Configuration_des_contacts="" Courant="" Courant_de_contact_max_="" CurrentDate="19/04/2016" CurrentTime="15:38:07" Date="" Date_de_cr_ation="" Derni_re_r_vision="" Description="" Designator="C1" Designator_X_Mil_="1260" Designator_X_mm_="32.004" Designator_Y_Mil_="6749.892" Designator_Y_mm_="171.447" DesignItemId="C_47&#181;F" Document="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentName="Arduino.SchDoc" DocumentNumber="" DrawnBy="" Edition="" Engineer="" Fabriquant="" Footprint="C_5mm" Force__fonctionnement="" Hauteur="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="1" ItemGUID="" Library_Name="Capas_Chimiques.IntLib" Library_Reference="C_47&#181;F" LibRef="C_47&#181;F" Lien_GCC="" LogicalDesignator="C1" Manufacturer="PANASONIC" Manufacturer_1="PANASONIC ELECTRONIC COMPONENTS" Manufacturer_Part_Number="ECA1EM470" Manufacturer_Part_Number_1="ECA1EM470" Model_Footprint="" Models="1" ModifiedDate="19/04/2016" MSL="" Organization="" PartType="47&#181;F" PCB3D="" PhysicalPath="Arduino" Pic_de_longueur_d_onde="" Pins="2" Poid="" Pricing="5&#61;0.088, 50&#61;0.085, 100&#61;0.058, 500&#61;0.046, 1000&#61;0.039 &#40;EUR&#41;" Prix="" Project="C:&#92;PSTE Carte/Carte Temp&#92;Carte temp&#92;Carte temp.PrjPcb" ProjectName="Carte temp.PrjPcb" Puissance="" Puissance_lumineuse="" Quantity="1" R_f_rence_fabriquant="" Revision="" RevisionGUID="" Rule="" Semi_conducteur="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="Capas_Chimiques.IntLib" Sub_Parts="1" Supplier_1="Farnell" Supplier_Currency_1="GBP" Supplier_Order_Qty_1="1" Supplier_Part_Number_1="1848498" Supplier_Stock_1="2061" Supplier_Subtotal_1="" Supplier_Unit_Price_1="" SVHC="" Tension="" Tension_DC_nominale_du_contact="" Terminaisons_commutateur="" Time="" Title="" Tr="" Type="" Type_d_actionnement="" UniqueIdName="SJCYULDQ" UniqueIdPath="" Variant="" VaultGUID="" Vd="" _="1" _ID_="1414984896" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Angle_de_diffusion="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Code_JEITA="" Comment="47&#181;F" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink1URL="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink2Description="http://www.farnell.com/cad/1703907.zip" ComponentLink2URL="http://www.farnell.com/cad/1703907.zip" Configuration_des_contacts="" Courant="" Courant_de_contact_max_="" CurrentDate="19/04/2016" CurrentTime="15:38:07" Date="" Date_de_cr_ation="" Derni_re_r_vision="" Description="" Designator="C2" Designator_X_Mil_="5060" Designator_X_mm_="128.524" Designator_Y_Mil_="6849.892" Designator_Y_mm_="173.987" DesignItemId="C_47&#181;F" Document="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentName="Arduino.SchDoc" DocumentNumber="" DrawnBy="" Edition="" Engineer="" Fabriquant="" Footprint="C_5mm" Force__fonctionnement="" Hauteur="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="2" ItemGUID="" Library_Name="Capas_Chimiques.IntLib" Library_Reference="C_47&#181;F" LibRef="C_47&#181;F" Lien_GCC="" LogicalDesignator="C2" Manufacturer="PANASONIC" Manufacturer_1="PANASONIC ELECTRONIC COMPONENTS" Manufacturer_Part_Number="ECA1EM470" Manufacturer_Part_Number_1="ECA1EM470" Model_Footprint="" Models="1" ModifiedDate="19/04/2016" MSL="" Organization="" PartType="47&#181;F" PCB3D="" PhysicalPath="Arduino" Pic_de_longueur_d_onde="" Pins="2" Poid="" Pricing="5&#61;0.088, 50&#61;0.085, 100&#61;0.058, 500&#61;0.046, 1000&#61;0.039 &#40;EUR&#41;" Prix="" Project="C:&#92;PSTE Carte/Carte Temp&#92;Carte temp&#92;Carte temp.PrjPcb" ProjectName="Carte temp.PrjPcb" Puissance="" Puissance_lumineuse="" Quantity="1" R_f_rence_fabriquant="" Revision="" RevisionGUID="" Rule="" Semi_conducteur="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="Capas_Chimiques.IntLib" Sub_Parts="1" Supplier_1="Farnell" Supplier_Currency_1="GBP" Supplier_Order_Qty_1="1" Supplier_Part_Number_1="1848498" Supplier_Stock_1="2061" Supplier_Subtotal_1="" Supplier_Unit_Price_1="" SVHC="" Tension="" Tension_DC_nominale_du_contact="" Terminaisons_commutateur="" Time="" Title="" Tr="" Type="" Type_d_actionnement="" UniqueIdName="YTLGEHKP" UniqueIdPath="" Variant="" VaultGUID="" Vd="" _="2" _ID_="1414985280" _PARENTID_=""></ROW>
    <ROW Address1="" Address2="" Address3="" Address4="" Angle_de_diffusion="" Application_BuildNumber="" ApprovedBy="" Author="" CheckedBy="" Code_IPC="" Code_JEDEC="" Code_JEITA="" Comment="47&#181;F" CompanyName="" Component_Kind="Standard" ComponentKind="0" ComponentLink1Description="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink1URL="http://www.farnell.com/datasheets/1678745.pdf" ComponentLink2Description="http://www.farnell.com/cad/1703907.zip" ComponentLink2URL="http://www.farnell.com/cad/1703907.zip" Configuration_des_contacts="" Courant="" Courant_de_contact_max_="" CurrentDate="19/04/2016" CurrentTime="15:38:07" Date="" Date_de_cr_ation="" Derni_re_r_vision="" Description="" Designator="C3" Designator_X_Mil_="8150" Designator_X_mm_="207.01" Designator_Y_Mil_="2110" Designator_Y_mm_="53.594" DesignItemId="C_47&#181;F" Document="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentFullPathAndName="C:&#92;Users&#92;Remy&#92;ownCloud&#92;PSTE&#92;Electronique&#92;ShieldBBGaliV v2&#92;Arduino.SchDoc" DocumentName="Arduino.SchDoc" DocumentNumber="" DrawnBy="" Edition="" Engineer="" Fabriquant="" Footprint="C_5mm" Force__fonctionnement="" Hauteur="" Height_Mil_="0" Height_mm_="0" Ibis_Model="" ImagePath="" Index="3" ItemGUID="" Library_Name="Capas_Chimiques.IntLib" Library_Reference="C_47&#181;F" LibRef="C_47&#181;F" Lien_GCC="" LogicalDesignator="C3" Manufacturer="PANASONIC" Manufacturer_1="PANASONIC ELECTRONIC COMPONENTS" Manufacturer_Part_Number="ECA1EM470" Manufacturer_Part_Number_1="ECA1EM470" Model_Footprint="" Models="1" ModifiedDate="19/04/2016" MSL="" Organization="" PartType="47&#181;F" PCB3D="" PhysicalPath="Arduino" Pic_de_longueur_d_onde="" Pins="2" Poid="" Pricing="5&#61;0.088, 50&#61;0.085, 100&#61;0.058, 500&#61;0.046, 1000&#61;0.039 &#40;EUR&#41;" Prix="" Project="C:&#92;PSTE Carte/Carte Temp&#92;Carte temp&#92;Carte temp.PrjPcb" ProjectName="Carte temp.PrjPcb" Puissance="" Puissance_lumineuse="" Quantity="1" R_f_rence_fabriquant="" Revision="" RevisionGUID="" Rule="" Semi_conducteur="" SheetNumber="" SheetTotal="1" Signal_Integrity="" Simulation="" SourceLibraryName="Capas_Chimiques.IntLib" Sub_Parts="1" Supplier_1="Farnell" Supplier_Currency_1="GBP" Supplier_Order_Qty_1="1" Supplier_Part_Number_1="1848498" Supplier_Stock_1="2061" Supplier_Subtotal_1="" Supplier_Unit_Price_1="" SVHC="" Tension="" Tension_DC_nominale_du_contact="" Terminaisons_commutateur="" Time="" Title="" Tr="" Type="" Type_d_actionnement="" UniqueIdName="CVOHECDH" UniqueIdPath="" Variant="" VaultGUID="" Vd="" _="3" _ID_="1414985184" _PARENTID_=""></ROW>